export enum Icons {
    Equalizer = 'equalizer',
    Settings = 'settings',
    Edit = 'edit',
    Delete = 'delete',
    Menu = 'menu',
    Plus = 'plus',
    Increase = 'increase',
    Decrease = 'decrease',
    Arrow = 'arrow',
    Focus = 'focus',
    Clock = 'clock',
    Stop = 'stop',
    Close = 'close',
}